#!/usr/bin/env python3

# Copyright © 2004-2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import sys

def stred(lst):
    if lst:
        return ' '.join(map(str, lst))
    else:
        return '0'

def main():
    s = [line.rstrip('\r\n') for line in sys.stdin]
    width = len(s[0])
    height = len(s)
    print(width, height)
    for y in range(height):
        c = 0
        lst = []
        prev = ' '
        for x in range(width):
            curr = s[y][x]
            if (prev == 'X') & (curr == ' '):
                lst.append(c)
                c = 0
            elif (curr == 'X'):
                c = c+1
            prev = curr
        if c > 0:
            lst.append(c)
        print(stred(lst))
    for x in range(width):
        c = 0
        lst = []
        prev = ' '
        for y in range(height):
            curr = s[y][x]
            if (prev == 'X') & (curr == ' '):
                lst.append(c)
                c = 0
            elif (curr == 'X'):
                c = c+1
            prev = curr
        if c > 0:
            lst.append(c)
        print(stred(lst))

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
